openapi: 3.0.0
tags:
  - name: Posts manager api

parameters:
  - in: path
    name: id
    description: ID of the post
    required: true
  - name: UserId
    description: ID of the user
    required: true
  - name: title
    description: Title of the post
    required: false
  - name: body
    description: Body of the post
    required: false

responses:
    '200':
      description: Successful update
    '401':
      description: You are not authorised to update this post.
    '404':
      description: We could not find this post.Try typing in its ID or the ID of its creator.
    '500':
      description: Internal Server Error